# -------------------------------
# This is my first automated test
# -------------------------------
name: My-AutomatedTest-Assignment

on:
 push:
  branches:
    - main
  # pull_request:
  #  branches:
  #    - main

jobs:
  musclemeat-testing-login-Edge:
    runs-on: ubuntu-latest
    if: github.event == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Run musclemeat login test in Edge
        run: npm run test1
    
      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          name: Musclemeat login result Edge
          path: /home/runner/work/MuscleMeat/MuscleMeat/cypress/videos/loginMuscleMeat.cy.js.mp4

  musclemeat-testing-login-Chrome:
            runs-on: ubuntu-latest
            # if: github.event == 'pull_request'
        
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
                
              - name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: 18
        
              - name: Install dependencies
                run: npm install
              
              - name: Run musclemeat login test in Chrome
                run: npm run test2
            
              - name: Upload video
                uses: actions/upload-artifact@v3
                with:
                  name: Musclemeat login result Chrome
                  path: /home/runner/work/MuscleMeat/MuscleMeat/cypress/videos/loginMuscleMeat.cy.js.mp4
    
  # obtaining-musclemeat-results-video:
  #   runs-on: ubuntu-latest
  #   needs: musclemeat-testing-login

  #   steps:
  #     - name: Download video
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: Musclemeat login result
          
  #     - name: Display structure of downloaded files
  #       run: ls -R

